[build]
  command = "npm run build"
  publish = "dist/erma-zafe/browser"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/angular-runtime"
  
  [plugins.inputs]
    disabled = true